### ISSUE TITLE
[BUG] TypeError: undefined is not an object (evaluating 'cyptoObj.getRandomValues') - Looks to be an issue with the power bi client library when running on IOS.  

### ISSUE THREAD

**Issue by S-J-D-13** [akshay5995/powerbi-report-component#239]
I am getting the above error when trying to use the package. See full message: 

![IMG_0607](https://user-images.githubusercontent.com/32793990/83118267-0f5ddd80-a0c6-11ea-8613-ee769de9b56a.PNG)
 
I am fairly new to react native so it probably my fault but I have followed the documentation and can't find out how to fix as it is part of the dependency not my code?

**Comment by akshay5995** [comment]
Hi @S-J-D-13, It looks like it's an issue with powerbi.js a core dependency of this package. I'm not sure if it's a big of this package.

**Comment by akshay5995** [comment]
Closing as the bug's not related to the library.

**Comment by sftsk** [comment]
The issue seems to have to do with this: https://github.com/react-native-community/discussions-and-proposals/issues/83
The crypto library to generate unique ids is not included in react-native.

This should be a workaround if you are using react-native normally: https://github.com/LinusU/react-native-get-random-values , this might eventually become at a workaround if you work with Expo: https://github.com/expo/expo/issues/7209
